- name: Install Docker and Run Jenkins
  hosts: cicd
  become: true
  
  tasks:
    - name: Install prerequisite packages
      apt:
        name: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common", "python3-pip"]
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: Check Docker version
      command: docker --version
      register: docker_version_output


    - name: Debug Docker version
      debug:
        msg: "{{ docker_version_output.stdout }}"

    - name: Pull Jenkins Docker image
      shell: docker pull jenkins/jenkins
      become: yes

    - name: Run Jenkins container
      shell: |
        docker run -d --name jenkins_container -p 8080:8080 jenkins/jenkins
      become: yes

    - name: Verify Jenkins is running
      shell: docker ps
      register: docker_ps_output

    - name: Display Docker ps output
      debug:
        msg: "{{ docker_ps_output.stdout_lines }}"
