aws_region      = "us-east-1"
key_name        = "deployer-key"
public_key_path = "/home/mahmoud/.ssh/deployer-key.pub"
instance_type   = "t2.micro"
ami_id          = "ami-04b4f1a9cf54c11d0"
cidr_block      = "0.0.0.0/0"
